theme[main_bg]="#1A1620"
theme[main_fg]="#FF69B4"
theme[title]="#00BCD4"
theme[hi_fg]="#00BCD4"
theme[proc_misc]="#FF69B4"
theme[cpu_box]="#00E5FF"
theme[mem_box]="#00E5FF"
theme[net_box]="#00E5FF"
theme[proc_box]="#00E5FF"
theme[div_line]="#005F5F"

theme[temp_start]="#FF85C2"
theme[temp_mid]="#00E5FF"
theme[temp_end]="#FF1493"

theme[cpu_start]="#FF85C2"
theme[cpu_mid]="#00E5FF"
theme[cpu_end]="#FF1493"

theme[free_start]="#FF85C2"
theme[free_mid]="#00E5FF"
theme[free_end]="#FF85C2"

theme[cached_start]="#00BCD4"
theme[cached_mid]="#00BCD4"
theme[cached_end]="#00BCD4"

theme[available_start]="#FF85C2"
theme[available_mid]="#00E5FF"
theme[available_end]="#FF85C2"

theme[used_start]="#FF85C2"
theme[used_mid]="#00E5FF"
theme[used_end]="#FF85C2"

theme[download_start]="#FF85C2"
theme[download_mid]="#00E5FF"
theme[download_end]="#FF1493"

theme[upload_start]="#FF85C2"
theme[upload_mid]="#00E5FF"
theme[upload_end]="#FF1493"
