accent = "#00BCD4"
cursor = "#00E5FF"
foreground = "#FF69B4"
background = "#1A1620"
selection_foreground = "#FFB6C1"
selection_background = "#003333"

color0 = "#008B8B"
color1 = "#00BCD4"
color2 = "#00E5FF"
color3 = "#00E5FF"
color4 = "#00E5FF"
color5 = "#00BCD4"
color6 = "#00E5FF"
color7 = "#FFB6C1"
color8 = "#008B8B"
color9 = "#00E5FF"
color10 = "#00E5FF"
color11 = "#00E5FF"
color12 = "#00E5FF"
color13 = "#00BCD4"
color14 = "#00E5FF"
color15 = "#FFC0CB"
