$color = rgba(0, 229, 255, 1)
$inner_color = rgba(0, 229, 255, 0.85)
$outer_color = rgba(0, 188, 212, 1)
$font_color = rgba(255, 105, 180, 1)
$placeholder_color = rgba(204, 0, 102, 0.6)
$check_color = rgba(0, 188, 212, 1)
