background #1A1620
foreground #FF85C2

selection_background #003333
selection_foreground #FF85C2

cursor #FF1493
cursor_text_color #1A1620

black   #005F5F
red     #FF1493
green   #FF85C2
yellow  #FF85C2
blue    #FF1493
magenta #FF1493
cyan    #FF85C2
white   #E0FFFF

bright_black   #008B8B
bright_red     #FF85C2
bright_green   #FF85C2
bright_yellow  #FF85C2
bright_blue    #FF1493
bright_magenta #FF1493
bright_cyan    #FF85C2
bright_white   #E0FFFF

mark1_foreground #1A1620
mark1_background #FF1493
mark2_foreground #1A1620
mark2_background #FF1493

# Cursor animation
cursor_trail 1
